-- 035_stacks_full_menu.sql
--
-- Replace the small hand-seeded Stacks menu (from 015) with the full,
-- real, priced menu scraped from the live ordering page:
--   https://www.stacks66.com/order/glendora
--
-- Item names are kept verbatim (the diner presents them in ALL CAPS);
-- prices are the exact online-ordering prices in USD. A few POS-only
-- artifacts were dropped: a literal "(Copy)" side, one duplicate
-- "S/ TRI-TIP", and the duplicate "KIDS DRINKS WEST" category (identical
-- to "KIDS DRINKS"). Dollar-quoted to avoid escaping apostrophes.

update public.template_locations l
   set menu = $json$
{
  "version": 1,
  "currency_default": "USD",
  "categories": [
    {"id":"popular","name":"Popular","description":"Crowd favorites","items":[
      {"id":"pop-1","name":"DENVER OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"pop-2","name":"PORK CHOP & EGGS","price":{"amount":25.99,"currency":"USD"}},
      {"id":"pop-3","name":"TRI TIP & EGGS","price":{"amount":29.99,"currency":"USD"}}
    ]},
    {"id":"breakfast","name":"Breakfast","items":[
      {"id":"bk-1","name":"TRI TIP & EGGS","price":{"amount":29.99,"currency":"USD"}},
      {"id":"bk-2","name":"PORK CHOP & EGGS","price":{"amount":25.99,"currency":"USD"}},
      {"id":"bk-3","name":"1/2 BACON 1/2 SAUSAGE","price":{"amount":18.99,"currency":"USD"}},
      {"id":"bk-4","name":"BACON & EGGS","price":{"amount":18.99,"currency":"USD"}},
      {"id":"bk-5","name":"BURGER PATTY & EGGS 1/2 lb","price":{"amount":22.99,"currency":"USD"}},
      {"id":"bk-6","name":"CANADIAN BACON & EGGS","price":{"amount":20.99,"currency":"USD"}},
      {"id":"bk-7","name":"CHICKEN & EGGS","price":{"amount":22.99,"currency":"USD"}},
      {"id":"bk-8","name":"CORNED BEEF & EGGS","price":{"amount":20.99,"currency":"USD"}},
      {"id":"bk-9","name":"DICED HAM & EGGS","price":{"amount":19.99,"currency":"USD"}},
      {"id":"bk-10","name":"FRIED STEAK & EGGS","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bk-11","name":"HAM & EGGS","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bk-12","name":"2 EGGS & HASHBROWNS","price":{"amount":16.99,"currency":"USD"}},
      {"id":"bk-13","name":"POLISH SAUSAGE & EGGS","price":{"amount":20.99,"currency":"USD"}},
      {"id":"bk-14","name":"SAUSAGE LINKS & EGGS","price":{"amount":19.99,"currency":"USD"}},
      {"id":"bk-15","name":"SAUSAGE PATTY & EGGS","price":{"amount":15.99,"currency":"USD"}},
      {"id":"bk-16","name":"TURKEY BURGER PATTY & EGGS","price":{"amount":22.99,"currency":"USD"}},
      {"id":"bk-17","name":"TURKEY BACON & EGGS","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bk-18","name":"TURKEY SAUSAGE (PATTY) & EGGS","price":{"amount":17.99,"currency":"USD"}},
      {"id":"bk-19","name":"VEGGIE PATTY & EGGS","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bk-20","name":"BREAKFAST CREPES","price":{"amount":19.99,"currency":"USD"}}
    ]},
    {"id":"breakfast-wraps","name":"Breakfast Wraps","items":[
      {"id":"bw-1","name":"2+2 GLUTEN FREE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"bw-2","name":"2+2+2","price":{"amount":17.99,"currency":"USD"}},
      {"id":"bw-3","name":"2+2+HAM","price":{"amount":20.99,"currency":"USD"}},
      {"id":"bw-4","name":"2+2+HASH","price":{"amount":18.99,"currency":"USD"}},
      {"id":"bw-5","name":"AVOCADO TOAST","price":{"amount":17.99,"currency":"USD"}},
      {"id":"bw-6","name":"BREAKFAST WRAP","price":{"amount":20.99,"currency":"USD"}},
      {"id":"bw-7","name":"CHORIZO WRAP","price":{"amount":17.99,"currency":"USD"}},
      {"id":"bw-8","name":"COUNTRY BREAKFAST","price":{"amount":18.99,"currency":"USD"}},
      {"id":"bw-9","name":"HAWAIIAN DELIGHT","price":{"amount":19.99,"currency":"USD"}},
      {"id":"bw-10","name":"SPARTAN","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bw-11","name":"VEGGIE WRAP","price":{"amount":19.99,"currency":"USD"}}
    ]},
    {"id":"breakfast-specials","name":"Breakfast Specials","items":[
      {"id":"bs-1","name":"BREAKFAST SPECIAL","price":{"amount":14.99,"currency":"USD"}},
      {"id":"bs-2","name":"County Brkst / Spec","price":{"amount":16.99,"currency":"USD"}},
      {"id":"bs-3","name":"Oats And Coffee Spec","price":{"amount":13.99,"currency":"USD"}},
      {"id":"bs-4","name":"Oats Plus Fruit/ Toast","price":{"amount":13.99,"currency":"USD"}},
      {"id":"bs-5","name":"Panck / Eggs Spec","price":{"amount":12.99,"currency":"USD"}},
      {"id":"bs-6","name":"Two Egg / Spec","price":{"amount":12.99,"currency":"USD"}}
    ]},
    {"id":"omelettes","name":"Omelettes","items":[
      {"id":"om-1","name":"DENVER OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-2","name":"ATHENIAN OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-3","name":"BACON & CHEESE OMELETTE","price":{"amount":17.99,"currency":"USD"}},
      {"id":"om-4","name":"BROCCOLI & CHEESE OMELETTE","price":{"amount":20.99,"currency":"USD"}},
      {"id":"om-5","name":"DOUBLE CHEESE OMELETTE","price":{"amount":19.99,"currency":"USD"}},
      {"id":"om-6","name":"EL PASO OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-7","name":"HAM & CHEESE OMELETTE","price":{"amount":18.99,"currency":"USD"}},
      {"id":"om-8","name":"STACKS FAVORITE OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-9","name":"MEDITERRANEAN OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-10","name":"MUSHROOM & SWISS OMELETTE","price":{"amount":21.99,"currency":"USD"}},
      {"id":"om-11","name":"NEPTUNE OMELETTE","price":{"amount":23.99,"currency":"USD"}},
      {"id":"om-12","name":"POLISH SAUSAGE OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-13","name":"NEW MEXICO OMELETTE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"om-14","name":"PLAIN OMELETTE","price":{"amount":19.99,"currency":"USD"}},
      {"id":"om-15","name":"SANTA MONICA OMELETTE","price":{"amount":25.99,"currency":"USD"}},
      {"id":"om-16","name":"SAUSAGE & CHEESE OMELETTE","price":{"amount":19.99,"currency":"USD"}},
      {"id":"om-17","name":"SPINACH & FETA OMELETTE","price":{"amount":21.99,"currency":"USD"}},
      {"id":"om-18","name":"TEXAS OMELETTE","price":{"amount":28.99,"currency":"USD"}},
      {"id":"om-19","name":"TURKEY AVOCADO OMELETTE","price":{"amount":26.99,"currency":"USD"}},
      {"id":"om-20","name":"TURKEY BACON OMELETTE","price":{"amount":26.99,"currency":"USD"}},
      {"id":"om-21","name":"TURKEY SAUSAGE OMELETTE","price":{"amount":23.99,"currency":"USD"}},
      {"id":"om-22","name":"VEGGIE OMELETTE","price":{"amount":21.99,"currency":"USD"}},
      {"id":"om-23","name":"WEST COAST OMELETTE","price":{"amount":25.99,"currency":"USD"}}
    ]},
    {"id":"skillets","name":"Skillets","items":[
      {"id":"sk-1","name":"ATHENIAN SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-2","name":"CALI SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-3","name":"CHICAGO SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-4","name":"COUNTRY SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-5","name":"DENVER SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-6","name":"STACKS FAV SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-7","name":"OKLAHOMA SKILLET","price":{"amount":20.99,"currency":"USD"}},
      {"id":"sk-8","name":"POLISH SAUSAGE SKILLET","price":{"amount":20.99,"currency":"USD"}},
      {"id":"sk-9","name":"SANTA FE SKILLET","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sk-10","name":"TEXAS SKILLET","price":{"amount":24.99,"currency":"USD"}},
      {"id":"sk-11","name":"WEST COAST SKILLET","price":{"amount":25.99,"currency":"USD"}}
    ]},
    {"id":"flappys-fitness","name":"Flappy's Fitness","items":[
      {"id":"ff-1","name":"ALEXANDER'S FAVORITE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"ff-2","name":"HAWAIIAN DELIGHT","price":{"amount":19.99,"currency":"USD"}},
      {"id":"ff-3","name":"JACK'S BREAKFAST","price":{"amount":22.99,"currency":"USD"}},
      {"id":"ff-4","name":"LEONIDA'S FAVORITE","price":{"amount":22.99,"currency":"USD"}},
      {"id":"ff-5","name":"THE FITNESS OMELETTE","price":{"amount":26.99,"currency":"USD"}},
      {"id":"ff-6","name":"THE WARM UP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"ff-7","name":"TONYA'S BREAKFAST","price":{"amount":19.99,"currency":"USD"}}
    ]},
    {"id":"bennys-corner","name":"Benny's Corner","items":[
      {"id":"bc-1","name":"CLASSIC BENEDICT","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bc-2","name":"COUNTRY BENEDICT","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bc-3","name":"CRAB BENEDICT","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bc-4","name":"IRISH BENEDICT","price":{"amount":21.99,"currency":"USD"}},
      {"id":"bc-5","name":"VEGGIE BENEDICT","price":{"amount":21.99,"currency":"USD"}}
    ]},
    {"id":"classic-burgers","name":"Classic Burgers","items":[
      {"id":"cb-1","name":"CALIFORNIA BURGER","price":{"amount":20.99,"currency":"USD"}},
      {"id":"cb-2","name":"JACK'S BURGER","price":{"amount":22.99,"currency":"USD"}},
      {"id":"cb-3","name":"MUSHROOM BURGER","price":{"amount":20.99,"currency":"USD"}},
      {"id":"cb-4","name":"PATTY MELT BURGER","price":{"amount":18.99,"currency":"USD"}},
      {"id":"cb-5","name":"ROUTE 66 BURGER","price":{"amount":19.99,"currency":"USD"}},
      {"id":"cb-6","name":"TURKEY BURGER","price":{"amount":18.99,"currency":"USD"}},
      {"id":"cb-7","name":"VEGGIE BURGER","price":{"amount":18.99,"currency":"USD"}}
    ]},
    {"id":"sandwiches","name":"Sandwiches","items":[
      {"id":"sw-1","name":"BLT","price":{"amount":18.99,"currency":"USD"}},
      {"id":"sw-2","name":"BUFFALO CHICKEN SANDWICH","price":{"amount":19.99,"currency":"USD"}},
      {"id":"sw-3","name":"CLUB","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sw-4","name":"COLD HAM & CHEESE SANDWICH","price":{"amount":19.99,"currency":"USD"}},
      {"id":"sw-5","name":"EGG SANDWICH","price":{"amount":17.99,"currency":"USD"}},
      {"id":"sw-6","name":"FRENCH DIP","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-7","name":"FRISCO BEEF","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sw-8","name":"GRILLED CHEESE","price":{"amount":17.99,"currency":"USD"}},
      {"id":"sw-9","name":"MALIBU CHICKEN SANDWICH","price":{"amount":23.99,"currency":"USD"}},
      {"id":"sw-10","name":"MONTE CRISTO","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-11","name":"PASTRAMI SANDWICH","price":{"amount":19.99,"currency":"USD"}},
      {"id":"sw-12","name":"RANCH CHICKEN","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-13","name":"SANTA FE CHICKEN","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-14","name":"STEAK SANDWICH","price":{"amount":28.99,"currency":"USD"}},
      {"id":"sw-15","name":"THE SANTA MONICAN","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sw-16","name":"TUNA & AVOCADO","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-17","name":"TUNA MELT","price":{"amount":20.99,"currency":"USD"}},
      {"id":"sw-18","name":"TUNA SANDWICH","price":{"amount":20.99,"currency":"USD"}},
      {"id":"sw-19","name":"TURKEY AVO MELT","price":{"amount":21.99,"currency":"USD"}},
      {"id":"sw-20","name":"TURKEY SANDWICH","price":{"amount":20.99,"currency":"USD"}},
      {"id":"sw-21","name":"GRILLED CHICKEN SAND NEW","price":{"amount":21.99,"currency":"USD"}}
    ]},
    {"id":"soup-salad","name":"Soup & Salad","items":[
      {"id":"ss-1","name":"ASIAN CHICKEN SALAD","price":{"amount":21.99,"currency":"USD"}},
      {"id":"ss-2","name":"BUFFALO CRISPY CHICKEN SALAD","price":{"amount":21.99,"currency":"USD"}},
      {"id":"ss-3","name":"CALIFORNIA CHICKEN SALAD","price":{"amount":22.99,"currency":"USD"}},
      {"id":"ss-4","name":"COBB SALAD","price":{"amount":21.99,"currency":"USD"}},
      {"id":"ss-5","name":"FRENCH ONION SOUP","price":{"amount":10.99,"currency":"USD"}},
      {"id":"ss-6","name":"GARDEN SALAD","price":{"amount":12.99,"currency":"USD"}},
      {"id":"ss-7","name":"GREEK SALAD","price":{"amount":20.99,"currency":"USD"}},
      {"id":"ss-8","name":"JULIENNE SALAD","price":{"amount":21.99,"currency":"USD"}},
      {"id":"ss-9","name":"SOUP & SALAD","price":{"amount":17.99,"currency":"USD"}},
      {"id":"ss-10","name":"SOUP OF THE DAY","price":{"amount":9.99,"currency":"USD"}},
      {"id":"ss-11","name":"TRADITIONAL CAESAR SALAD","price":{"amount":19.99,"currency":"USD"}},
      {"id":"ss-12","name":"TRI-TIP SALAD","price":{"amount":29.99,"currency":"USD"}},
      {"id":"ss-13","name":"BEET SALAD","price":{"amount":18.99,"currency":"USD"}}
    ]},
    {"id":"wraps","name":"Wraps","items":[
      {"id":"wr-1","name":"BUFFALO CHICKEN WRAP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"wr-2","name":"CHICKEN CAESAR WRAP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"wr-3","name":"CHIPOTLE CHICKEN WRAP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"wr-4","name":"GREEK CHICKEN WRAP","price":{"amount":21.99,"currency":"USD"}},
      {"id":"wr-5","name":"LUNCH VEGGIE WRAP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"wr-6","name":"TURKEY AVOCADO RANCH WRAP","price":{"amount":21.99,"currency":"USD"}}
    ]},
    {"id":"appetizers","name":"Appetizers","items":[
      {"id":"ap-1","name":"ARTICHOKE DIP","price":{"amount":19.99,"currency":"USD"}},
      {"id":"ap-2","name":"CALAMARI","price":{"amount":21.99,"currency":"USD"}},
      {"id":"ap-3","name":"MOZARELLA STICKS","price":{"amount":18.99,"currency":"USD"}},
      {"id":"ap-4","name":"CHICKEN WINGS COMBO","price":{"amount":31.99,"currency":"USD"}},
      {"id":"ap-5","name":"CHICKEN WINGS 5 PC","price":{"amount":10.99,"currency":"USD"}},
      {"id":"ap-6","name":"POPCORN SHRIMP","price":{"amount":20.99,"currency":"USD"}},
      {"id":"ap-7","name":"JALAPENO POPPERS","price":{"amount":18.99,"currency":"USD"}}
    ]},
    {"id":"salads","name":"Salads","items":[
      {"id":"sl-1","name":"Traditional Cobb Salad","price":{"amount":19.99,"currency":"USD"}},
      {"id":"sl-2","name":"Chicken Caesar Salad","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sl-3","name":"Berry Berry Salad","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sl-4","name":"Shrimp & Asparagus salad","price":{"amount":22.99,"currency":"USD"}},
      {"id":"sl-5","name":"Chinese Salad","price":{"amount":22.99,"currency":"USD"}}
    ]},
    {"id":"pasta","name":"Pasta","items":[
      {"id":"pa-1","name":"BACON OR HAM SPAGHETTI ALFREDO","price":{"amount":26.99,"currency":"USD"}},
      {"id":"pa-2","name":"CHICKEN OR SHRIMP FETTUCCINI","price":{"amount":28.99,"currency":"USD"}},
      {"id":"pa-3","name":"SHRIMP SPAGHETTI","price":{"amount":26.99,"currency":"USD"}}
    ]},
    {"id":"main-course","name":"Main Course","items":[
      {"id":"mc-1","name":"TERIYAKI SALMON","price":{"amount":26.99,"currency":"USD"}},
      {"id":"mc-2","name":"GRILLED SALMON FILET","price":{"amount":26.99,"currency":"USD"}},
      {"id":"mc-3","name":"GRILLED RIBEYE STEAK","price":{"amount":30.99,"currency":"USD"}},
      {"id":"mc-4","name":"POT ROAST","price":{"amount":27.99,"currency":"USD"}},
      {"id":"mc-5","name":"JAMBALAYA","price":{"amount":28.99,"currency":"USD"}},
      {"id":"mc-6","name":"FILET OF SOLE","price":{"amount":21.99,"currency":"USD"}},
      {"id":"mc-7","name":"FISH AND CHIPS","price":{"amount":19.99,"currency":"USD"}},
      {"id":"mc-8","name":"CHICKEN TENDERS PLATE","price":{"amount":20.99,"currency":"USD"}},
      {"id":"mc-9","name":"THANKSGIVING MEAL","price":{"amount":29.99,"currency":"USD"}}
    ]},
    {"id":"kids-menu","name":"Kids Menu","items":[
      {"id":"km-1","name":"KIDS MEAL","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-2","name":"KIDS BURGER","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-3","name":"KIDS CH BURGER","price":{"amount":9.79,"currency":"USD"}},
      {"id":"km-4","name":"KIDS CHICK BREAST","price":{"amount":10.89,"currency":"USD"}},
      {"id":"km-5","name":"KIDS CHICK STRIPS","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-6","name":"KIDS EGG MUFF","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-7","name":"KIDS FRENCH TOAST","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-8","name":"KIDS FRENCH TOAST/ EGG","price":{"amount":8.25,"currency":"USD"}},
      {"id":"km-9","name":"KIDS FRENCH TOAST/ MEAT","price":{"amount":9.79,"currency":"USD"}},
      {"id":"km-10","name":"KIDS FRENCH TOAST/ EGG MEAT","price":{"amount":10.89,"currency":"USD"}},
      {"id":"km-11","name":"KIDS GRILL CHEESE","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-12","name":"KIDS OMEL CHEESE","price":{"amount":9.79,"currency":"USD"}},
      {"id":"km-13","name":"KIDS OMEL MEAT","price":{"amount":10.89,"currency":"USD"}},
      {"id":"km-14","name":"MICKEY/ EGG","price":{"amount":8.36,"currency":"USD"}},
      {"id":"km-15","name":"MICKEY/ EGG MEAT","price":{"amount":10.89,"currency":"USD"}},
      {"id":"km-16","name":"MICKEY/ MEAT","price":{"amount":9.79,"currency":"USD"}},
      {"id":"km-17","name":"MICKEY PANCAKE","price":{"amount":8.69,"currency":"USD"}},
      {"id":"km-18","name":"SILVER DOLL/ EGG","price":{"amount":8.36,"currency":"USD"}},
      {"id":"km-19","name":"SILVER DOLL/ EGG MEAT","price":{"amount":10.89,"currency":"USD"}},
      {"id":"km-20","name":"SILVER DOLL/MEAT","price":{"amount":9.02,"currency":"USD"}},
      {"id":"km-21","name":"SILVER DOLL","price":{"amount":8.69,"currency":"USD"}}
    ]},
    {"id":"kids-drinks","name":"Kids Drinks","items":[
      {"id":"kd-1","name":"KIDS CHOC MILK","price":{"amount":4.29,"currency":"USD"}},
      {"id":"kd-2","name":"KIDS HOT CHOC","price":{"amount":4.29,"currency":"USD"}},
      {"id":"kd-3","name":"KIDS JUICE","price":{"amount":4.29,"currency":"USD"}},
      {"id":"kd-4","name":"KIDS MILK","price":{"amount":4.29,"currency":"USD"}},
      {"id":"kd-5","name":"KIDS SODA","price":{"amount":4.29,"currency":"USD"}}
    ]},
    {"id":"drinks","name":"Drinks","items":[
      {"id":"dr-1","name":"HOT COFFEE","price":{"amount":5.39,"currency":"USD"}},
      {"id":"dr-2","name":"DECAFF","price":{"amount":4.45,"currency":"USD"}},
      {"id":"dr-3","name":"ASSORTED SOFT DRINKS","price":{"amount":5.39,"currency":"USD"}},
      {"id":"dr-4","name":"ORANGE JUICE","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-5","name":"ICED TEA","price":{"amount":5.39,"currency":"USD"}},
      {"id":"dr-6","name":"HOT CHOCOLATE","price":{"amount":5.39,"currency":"USD"}},
      {"id":"dr-7","name":"RASPBERRY TEA","price":{"amount":5.39,"currency":"USD"}},
      {"id":"dr-8","name":"APPLE JUICE","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-9","name":"CRANBERRY JUICE","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-10","name":"GUAVA PASSION","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-11","name":"CHOC MILK","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-12","name":"MILK (WHOLE OR 2%)","price":{"amount":6.49,"currency":"USD"}},
      {"id":"dr-13","name":"TOM JUICE","price":{"amount":6.49,"currency":"USD"}}
    ]},
    {"id":"milkshakes","name":"Milkshakes","items":[
      {"id":"ms-1","name":"CARAMEL MILKSHAKE","price":{"amount":9.99,"currency":"USD"}},
      {"id":"ms-2","name":"CHOCOLATE MILKSHAKE","price":{"amount":9.99,"currency":"USD"}},
      {"id":"ms-3","name":"OREO MILKSHAKE","price":{"amount":9.99,"currency":"USD"}},
      {"id":"ms-4","name":"STRAWBERRY MILKSHAKE","price":{"amount":9.99,"currency":"USD"}},
      {"id":"ms-5","name":"VANILLA MILKSHAKE","price":{"amount":9.99,"currency":"USD"}}
    ]},
    {"id":"desserts","name":"Desserts","items":[
      {"id":"de-1","name":"BROWNIE WITH ICE CREAM","price":{"amount":11.99,"currency":"USD"}}
    ]},
    {"id":"side-orders","name":"Side Orders","items":[
      {"id":"so-1","name":"S/ 1/2 CHICKEN BREAST","price":{"amount":11.99,"currency":"USD"}},
      {"id":"so-2","name":"S/1 EGG","price":{"amount":3.19,"currency":"USD"}},
      {"id":"so-3","name":"S/ 1 EGG WHITE","price":{"amount":3.63,"currency":"USD"}},
      {"id":"so-4","name":"1 MULTI-GRAIN PANCAKE","price":{"amount":9.46,"currency":"USD"}},
      {"id":"so-5","name":"1 PANCAKE","price":{"amount":7.59,"currency":"USD"}},
      {"id":"so-6","name":"1 PC CHICKEN STRIP","price":{"amount":4.58,"currency":"USD"}},
      {"id":"so-7","name":"1 PC CRAB CAKE","price":{"amount":6.78,"currency":"USD"}},
      {"id":"so-8","name":"1/2 BIS AND GRAVY","price":{"amount":9.79,"currency":"USD"}},
      {"id":"so-9","name":"BANANA BREAD","price":{"amount":6.49,"currency":"USD"}},
      {"id":"so-10","name":"S/ CHICK TENDER (4) F/F","price":{"amount":15.29,"currency":"USD"}},
      {"id":"so-11","name":"S/ COLESLAW","price":{"amount":6.49,"currency":"USD"}},
      {"id":"so-12","name":"FULL BIS & GRAVY","price":{"amount":11.99,"currency":"USD"}},
      {"id":"so-13","name":"S /FRENCH FRIES","price":{"amount":6.69,"currency":"USD"}},
      {"id":"so-14","name":"S/ BACON (4)","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-15","name":"S/ CARAMEL","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-16","name":"S/ TRI-TIP","price":{"amount":21.89,"currency":"USD"}},
      {"id":"so-17","name":"S/ 1 JALAPENO","price":{"amount":3.52,"currency":"USD"}},
      {"id":"so-18","name":"S/ 1 BURGER PATTY (1/2 LB)","price":{"amount":10.34,"currency":"USD"}},
      {"id":"so-19","name":"S/ 1 BURGER PATTY (1/3)","price":{"amount":6.82,"currency":"USD"}},
      {"id":"so-20","name":"S/ 1/2 AVOCADO","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-21","name":"S/ 2 EGG WHITES","price":{"amount":6.26,"currency":"USD"}},
      {"id":"so-22","name":"S/ 2 EGGS","price":{"amount":5.38,"currency":"USD"}},
      {"id":"so-23","name":"S/ 2 PC BACON","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-24","name":"S/ 2 PC SAUSAGE","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-25","name":"S/ POLISH SAUSAGE (3)","price":{"amount":10.89,"currency":"USD"}},
      {"id":"so-26","name":"S/ APPLE SAUCE","price":{"amount":4.62,"currency":"USD"}},
      {"id":"so-27","name":"S/ BANANA","price":{"amount":3.81,"currency":"USD"}},
      {"id":"so-28","name":"S/ BLINTZ CHEESE","price":{"amount":6.49,"currency":"USD"}},
      {"id":"so-29","name":"S/ CANADIAN BACON (3)","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-30","name":"S/ CHEESE","price":{"amount":3.75,"currency":"USD"}},
      {"id":"so-31","name":"S/ CHOC CHIP","price":{"amount":3.52,"currency":"USD"}},
      {"id":"so-32","name":"S/ CHOC SYRUP","price":{"amount":3.52,"currency":"USD"}},
      {"id":"so-33","name":"S/ CHORIZO","price":{"amount":9.79,"currency":"USD"}},
      {"id":"so-34","name":"S/ CORNED BEEF HASH","price":{"amount":9.79,"currency":"USD"}},
      {"id":"so-35","name":"S/ COTTAGE CHEESE","price":{"amount":7.59,"currency":"USD"}},
      {"id":"so-36","name":"S/ COUNTRY GRAVY","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-37","name":"S/ CUPCAKE","price":{"amount":4.84,"currency":"USD"}},
      {"id":"so-38","name":"S/ DRESSING","price":{"amount":3.53,"currency":"USD"}},
      {"id":"so-39","name":"S/ FRIED STEAK","price":{"amount":10.56,"currency":"USD"}},
      {"id":"so-40","name":"S/ FRUIT","price":{"amount":7.59,"currency":"USD"}},
      {"id":"so-41","name":"S/ GARLIC BREAD","price":{"amount":4.84,"currency":"USD"}},
      {"id":"so-42","name":"S/ GRANOLA","price":{"amount":3.74,"currency":"USD"}},
      {"id":"so-43","name":"S/ GYRO MEAT","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-44","name":"S/ HAM (DELI)","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-45","name":"S/ HAM STEAK","price":{"amount":10.89,"currency":"USD"}},
      {"id":"so-46","name":"S/ HASH BROWNS","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-47","name":"S/ HOLLANDAISE SAUCE","price":{"amount":6.49,"currency":"USD"}},
      {"id":"so-48","name":"S/ LINGON BUTTER","price":{"amount":3.41,"currency":"USD"}},
      {"id":"so-49","name":"S/ MUSHROOMS","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-50","name":"S/ NUTELLA","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-51","name":"S/ NUTS","price":{"amount":3.74,"currency":"USD"}},
      {"id":"so-52","name":"S/ 1/2 BAC 1/2 SAUS","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-53","name":"S/ OLIVES","price":{"amount":4.62,"currency":"USD"}},
      {"id":"so-54","name":"S/ ONION RINGS","price":{"amount":10.89,"currency":"USD"}},
      {"id":"so-55","name":"S/ PASTA","price":{"amount":5.61,"currency":"USD"}},
      {"id":"so-56","name":"S/ PICKLES (3)","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-57","name":"S/ PORK CHOP (2)","price":{"amount":18.59,"currency":"USD"}},
      {"id":"so-58","name":"S/ ROUTE 66 FRIES","price":{"amount":7.99,"currency":"USD"}},
      {"id":"so-59","name":"S/ SALSA","price":{"amount":3.52,"currency":"USD"}},
      {"id":"so-60","name":"S/ SAUSAGE LINKS (4)","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-61","name":"S/ SAUSAGE PATTY (3)","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-62","name":"S/ SCOOP OF TUNA","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-63","name":"S/ SOUR CREAM","price":{"amount":5.17,"currency":"USD"}},
      {"id":"so-64","name":"S/ SPICY BACON","price":{"amount":8.25,"currency":"USD"}},
      {"id":"so-65","name":"S/ SPINACH","price":{"amount":4.29,"currency":"USD"}},
      {"id":"so-66","name":"S/ TOMATOES","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-67","name":"S/ TOPPING","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-68","name":"S/ TURKEY BACON(4)","price":{"amount":10.12,"currency":"USD"}},
      {"id":"so-69","name":"S/ WHIP CREAM","price":{"amount":4.07,"currency":"USD"}},
      {"id":"so-70","name":"S/ YOGURT","price":{"amount":7.59,"currency":"USD"}},
      {"id":"so-71","name":"S/ ZUCCHINI","price":{"amount":10.89,"currency":"USD"}},
      {"id":"so-72","name":"S/ TURK BURGER (1)","price":{"amount":9.24,"currency":"USD"}},
      {"id":"so-73","name":"S/ 1 BIS AND GRAVY","price":{"amount":8.69,"currency":"USD"}},
      {"id":"so-74","name":"S/ 1 BIS NO GRAVY","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-75","name":"S/ TOAST","price":{"amount":3.99,"currency":"USD"}},
      {"id":"so-76","name":"S/ TURKEY (DELI)","price":{"amount":9.79,"currency":"USD"}},
      {"id":"so-77","name":"S/ TURKEY SAUSAGE (3)","price":{"amount":10.89,"currency":"USD"}},
      {"id":"so-78","name":"S/ TOAST OR MUFFIN","price":{"amount":5.39,"currency":"USD"}},
      {"id":"so-79","name":"S/ TORTILLA","price":{"amount":6.16,"currency":"USD"}},
      {"id":"so-80","name":"S/ VEGGIE PATTY (1)","price":{"amount":8.14,"currency":"USD"}},
      {"id":"so-81","name":"S/ 2PC TURKEY BACON","price":{"amount":7.26,"currency":"USD"}},
      {"id":"so-82","name":"S/ 1 PUMPKIN PANCAKE","price":{"amount":8.98,"currency":"USD"}},
      {"id":"so-83","name":"S/ TEXAS STEAK","price":{"amount":11.99,"currency":"USD"}},
      {"id":"so-84","name":"S/ ICE CREAM (1 SCOOP)","price":{"amount":5.39,"currency":"USD"}}
    ]}
  ]
}
$json$::jsonb
  from public.template_brands b
  join public.template_organizations o on o.id = b.org_id
 where l.brand_id = b.id
   and b.slug = 'stacks'
   and o.slug = 'stacks-on-route-66';
